name: Destroy Resources

on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      # Terraform action you want to perform
      action:
        description: "Terraform Action to Perform"
        type: choice
        options:
          - Terraform_apply
          - Terraform_destroy

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          #aws-region: ${{ secrets.AWS_REGION }}
          aws-region: us-east-1

      - name: Empty S3 resource
        run: |
          aws s3 rm s3://statc-website-ramesh123456 --recursive

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform
        
      - name: Terraform Plan
        # env: 
        #   BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: terraform plan -lock=false
        working-directory: terraform
        
      - name: Terraform Apply
        # env: 
        #   TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
        run: terraform destroy -auto-approve
        working-directory: terraform

      # - name: Uploading Files to S3 Bucket
      #   run: | 
      #     aws s3 cp index.html s3://statc-website-ramesh123456/index.html
      #     aws s3 cp --recursive images/ s3://statc-website-ramesh123456/images/
      #     aws s3 cp --recursive styles/ s3://statc-website-ramesh123456/styles/  

#######################################################
# name: Listing S3 Buckets

# on: 
#   push:
#     branches:
#       - master
#   workflow_dispatch:

# jobs:
#   listing_buckets:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Set Up AWS  Crendentilas 
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ secrets.IAM_ROLE }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       - name: List S3 Buckets
#         env:
#           AWS_REGION: ${{ secrets.AWS_REGION }}
#         run: |
#           echo "Listing s3 Buckts"
#           aws s3 ls s3://ga-website123


###################
# jobs:
#   log_message:
#     runs-on: ubuntu-latest
#     steps:
#       - name: log
#         run: echo "The Workflow is working"
######################

        
